### ISSUE TITLE
requirements.txt not installing using Python 3.8 and 3.9

### ISSUE THREAD

**Issue by rennerocha** [sixfeetup/cookiecutter-sixiedjango#10]
- Create virtualenvs for Python `3.8.13` and `3.9.11` I used pyenv for that) and activate them
- In each virtualenv run `pip install -r requirements.txt`

The following error is returned by pip:

```Collecting typing-extensions>=3.10.0.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.10.0.0 from https://files.pythonhosted.org/packages/ed/d6/2afc375a8d55b8be879d6b4986d4f69f01115e795e36827fd3a40166028b/typing_extensions-4.3.0-py3-none-any.whl#sha256=25642c956049920a5aa49edcdd6ab1e06d7e5d467fc00e0506c44ac86fbfca02 (from black==22.1.0->-r requirements.txt (line 21))
```

It worked fine with `3.10.6`

**Comment by sfu-peter** [comment]
Is this the template requirements or the generated project requirements?

**Comment by rennerocha** [comment]
This one:
https://github.com/sixfeetup/cookiecutter-sixiedjango/blob/main/requirements.txt

**Comment by sfu-peter** [comment]
@rennerocha can you test the associated branch?
