### ISSUE TITLE
Add build and deployment steps to CI pipelines

### ISSUE THREAD

**Issue by rennerocha** [sixfeetup/cookiecutter-sixiedjango#119]
An improvement of #73 
We need to add image building and deployment scripts to Bitbucket Pipelines and Github Actions.
One possible approach is to add the commands and scripts needed into the `Makefile` so we can update the steps without need to duplicate the efforts in the different providers (Bitbucket and Github) and also to be able to run the steps in any environment.

**Comment by sjlawson** [comment]
one question about this - since SFU is moving away from bitbucket, is that to be removed from the acceptance criteria? @rennerocha @rochecompaan

**Comment by rochecompaan** [comment]
Ideally, we would like to continue to support Bitbucket since users external to SFU will likely use it.

**Comment by rochecompaan** [comment]
I'm closing this issue since building images were listed as a requirement in #73. We'll use ArgoCD for deployment, not the pipeline.
