### ISSUE TITLE
Update tests targets to run locally and in CI

### ISSUE THREAD

**Issue by rennerocha** [sixfeetup/cookiecutter-sixiedjango#120]
Related to #73 

Current `backend-test`, `frontend-test` and `test` targets in `Makefile` run the tests well inside CI environment. However they won't work perfectly in a local environment (we need to install a few libs and keep some services running). We can't use docker images in the CIs, so we need to figure out the best approach to make these targets to work in both environments (local and CI).

**Comment by rochecompaan** [comment]
Added as requirement to #73, closing this issue.
