### ISSUE TITLE
Terraform config to deploy k3s to an ec2 instance

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/cookiecutter-sixiedjango#66]
Create a terraform config to deploy k3s on a new ec2 instance. Set up a security group to only allow access on ports 80 (HTTP), 443 (HTTPS), and 6443 (Kubernetes API port). Add a README to document how to deploy the new cluster and set up access to the Kubernetes cluster.

**Comment by nvernooy** [comment]
Once Best passes QA use [sfu-best/terraform](https://bitbucket.org/sixfeetup/sfu-best/src/f30ed75fe79f2e952e5c05c6b30cc4354edf477a/terraform/?at=nvernooy%2FSFUP042-302-ec2-cluster) as template
