### ISSUE TITLE
Set up Cloudfront as CDN

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/cookiecutter-sixiedjango#67]
1. Set up separate Cloudfront configs for prod and sandbox.
2. Confiure Cloudfront  to forward frontend and API requests to k8s cluster running on k3s on ec2 instance.
2. Update the terraform config for Cloudfront to set the origin request policy to AllViewerExceptHostHeader and the caching policy to CachingOptimized. You will need to look in the AWS console to see what the IDs of these policies are, or we need to create custom matching policies and reference them in the Cloudfront config eg.:
```
  default_cache_behavior {
    allowed_methods        = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods         = ["GET", "HEAD"]
    viewer_protocol_policy = "redirect-to-https"
    target_origin_id       = data.aws_instance.ec2_dev_cluster.id
    cache_policy_id        = "your_caching_optimized_policy_id"
    origin_request_policy_id = "your_all_viewer_except_host_header_policy_id"
    forwarded_values {
      query_string = true
      cookies {
        forward = "all"
      }
    }
  }
```
3. Set up the origin as follows:
```
  origin {
    domain_name = var.cluster_domain
    origin_id   = data.aws_instance.ec2_prod_cluster.id
    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "match-viewer"
      origin_ssl_protocols   = ["TLSv1.1", "TLSv1.2"]
    }
  }
```
4. Set up ACM certificate.

**Comment by nvernooy** [comment]
Cloudfront set up in [hosting-terraform](https://bitbucket.org/sixfeetup/hosting-terraform/src/8ec5a4b3e464a4efa63ff8f6368da8e83135b150/aws/best/sandbox/?at=nvernooy%2FSFUP042-308-cloudnative-s3)
Maybe all files should be in the same repo?
