### ISSUE TITLE
ArgoCD for releases

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/cookiecutter-sixiedjango#77]
1. Create `k8s/argocd/applications.yaml` with the ArgoCD application definitions for both sandbox and prod.
2. Generate `k8s/argocd/repocreds.yaml` 
3. Document how to install argocd in the cluster.

**Comment by nvernooy** [comment]
Added argocd manifests and updated README
https://github.com/sixfeetup/cookiecutter-sixiedjango/pull/103

**Comment by nvernooy** [comment]
Updated ArgoCD manifests to be generated from templates.
