### ISSUE TITLE
ConfigMap for environment variables handling

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/cookiecutter-sixiedjango#79]

**Comment by nvernooy** [comment]
Use [kustomize](https://bitbucket.org/sixfeetup/sfu-best/src/f30ed75fe79f2e952e5c05c6b30cc4354edf477a/deploy/sandbox/kustomization.yaml?at=nvernooy%2FSFUP042-302-ec2-cluster) to handle prod and sandbox environment variable differences
