### ISSUE TITLE
s3 storage for static content and media uploads

### ISSUE THREAD

**Issue by rochecompaan** [sixfeetup/cookiecutter-sixiedjango#86]
1. Add s3 config to terraform add a bucket for static and media uploads
2. Update Django config to use django-storages with s3 as storage backend, eg.:
```
# STATIC
# ------------------------

STATICFILES_STORAGE = "config.settings.production.StaticRootS3Boto3Storage"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
...
# endregion
DEFAULT_FILE_STORAGE = "config.settings.production.MediaRootS3Boto3Storage"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
```
3. Update Cloudfront config to serve all static content and media uploads from s3 bucket.

**Comment by nvernooy** [comment]
Added s3 bucket in terraform 
Updated django config to use the bucket 
Add origins for static content in Cloudfront in https://github.com/sixfeetup/cookiecutter-sixiedjango/issues/67
