### ISSUE TITLE
Separate terraform state buckets for sandbox and prod

### ISSUE THREAD

**Issue by rochecompaan** [sixfeetup/cookiecutter-sixiedjango#87]
Currently, the prod and sandbox have conflicting s3 buckets for terraform state. Add a prefix to the bucket names to resolve the conflict.

**Comment by nvernooy** [comment]
Updated the bucket provisioning in `init.tf` to use prefix.

**Comment by nvernooy** [comment]
Differences between staging and prod are set by the `key` attribute in the backend block. Conflicts with existing bucket names are to be resolve manually.
